### ISSUE TITLE
What would be the difference to ragas

### ISSUE THREAD

**Issue by ogencoglu** [DeployQL/reps#1]
Thanks for the work!

A comparison documentation to `ragas` would be very helpful.

**Comment by mtbarta** [comment]
Great idea! I'll add a comparison to the readme.

Ragas is great for evaluating the generation step of RAG and provides LLM-based evals. Retri-evals is working towards understanding the retrieval step. With our integration with MTEB, retri-evals gives standard retrieval metrics like NDCG. 

Similar to Ragas, we want users to bring their own data, and we're working on ways to do that through synthetic data and labeling from LLMs.

**Comment by ogencoglu** [comment]
Thanks, looking forward to it.
